version: '3.8'

services:
  web:
    build: ./portfolio-copy
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./portfolio-copy:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=al
      - POSTGRES_PASSWORD=al
      - POSTGRES_DB=al_dev

volumes:
  postgres_data:

